const courseData = [
  {
    id: 1,
    courseName: "Web Development",
    status: "Ongoing",
    students: 30,
    timing: "10:00 AM - 12:00 PM",
    batch: "Batch A",
  },
  {
    id: 2,
    courseName: "Mobile App Development",
    status: "Completed",
    students: 25,
    timing: "2:00 PM - 4:00 PM",
    batch: "Batch B",
  },
  {
    id: 3,
    courseName: "Data Science",
    status: "Upcoming",
    students: 40,
    timing: "1:00 PM - 3:00 PM",
    batch: "Batch C",
  },
  {
    id: 4,
    courseName: "Graphic Design",
    status: "Ongoing",
    students: 20,
    timing: "11:00 AM - 1:00 PM",
    batch: "Batch D",
  },
  {
    id: 5,
    courseName: "Cybersecurity",
    status: "Completed",
    students: 35,
    timing: "9:00 AM - 11:00 AM",
    batch: "Batch E",
  },
  {
    id: 6,
    courseName: "Digital Marketing",
    status: "Upcoming",
    students: 50,
    timing: "3:00 PM - 5:00 PM",
    batch: "Batch F",
  },
  {
    id: 7,
    courseName: "Artificial Intelligence",
    status: "Ongoing",
    students: 28,
    timing: "4:00 PM - 6:00 PM",
    batch: "Batch G",
  },
  {
    id: 8,
    courseName: "UI/UX Design",
    status: "Completed",
    students: 18,
    timing: "12:00 PM - 2:00 PM",
    batch: "Batch H",
  },
  {
    id: 9,
    courseName: "Cloud Computing",
    status: "Upcoming",
    students: 45,
    timing: "1:30 PM - 3:30 PM",
    batch: "Batch I",
  },
  {
    id: 10,
    courseName: "Game Development",
    status: "Ongoing",
    students: 22,
    timing: "10:30 AM - 12:30 PM",
    batch: "Batch J",
  },
  {
    id: 11,
    courseName: "Development",
    status: "Ongoing",
    students: 22,
    timing: "10:30 AM - 12:30 PM",
    batch: "Batch M",
  },
  {
    id: 12,
    courseName: "Game",
    status: "Ongoing",
    students: 22,
    timing: "10:30 AM - 12:30 PM",
    batch: "Batch N",
  },
];

const studentsData = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    assignmentsSubmitted: 8,
    assignmentsRemaining: 2,
    totalAssignments: 10,
    result: "85%",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    assignmentsSubmitted: 5,
    assignmentsRemaining: 5,
    totalAssignments: 10,
    result: "75%",
  },
  {
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    assignmentsSubmitted: 9,
    assignmentsRemaining: 1,
    totalAssignments: 10,
    result: "90%",
  },
  {
    name: "Bob Brown",
    email: "bob.brown@example.com",
    assignmentsSubmitted: 6,
    assignmentsRemaining: 4,
    totalAssignments: 10,
    result: "70%",
  },
  {
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    assignmentsSubmitted: 10,
    assignmentsRemaining: 0,
    totalAssignments: 10,
    result: "95%",
  },
  {
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    assignmentsSubmitted: 7,
    assignmentsRemaining: 3,
    totalAssignments: 10,
    result: "80%",
  },
  {
    name: "Franklin Thomas",
    email: "franklin.thomas@example.com",
    assignmentsSubmitted: 4,
    assignmentsRemaining: 6,
    totalAssignments: 10,
    result: "60%",
  },
  {
    name: "Grace Lee",
    email: "grace.lee@example.com",
    assignmentsSubmitted: 8,
    assignmentsRemaining: 2,
    totalAssignments: 10,
    result: "85%",
  },
  {
    name: "Henry Adams",
    email: "henry.adams@example.com",
    assignmentsSubmitted: 3,
    assignmentsRemaining: 7,
    totalAssignments: 10,
    result: "50%",
  },
  {
    name: "Isabel White",
    email: "isabel.white@example.com",
    assignmentsSubmitted: 6,
    assignmentsRemaining: 4,
    totalAssignments: 10,
    result: "75%",
  },
];
export { courseData, studentsData };
